project_name: filebrowser

env:
  - GO111MODULE=on

build:
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/wutong-paas/filebrowser/v2/version.Version={{ .Version }} -X github.com/wutong-paas/filebrowser/v2/version.CommitSHA={{ .ShortCommit }}
  main: main.go
  binary: filebrowser
  goos:
    - linux
  goarch:
    - amd64
    - arm64

dockers:
  -
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64,linux/arm64"
    goos: linux
    goarch: amd64,arm64
    image_templates:
      - "wutongpaas/filebrowser"
    extra_files:
      - docker_config.json

docker_manifests:
  - name_template: "wutongpaas/filebrowser:latest"
    image_templates:
      - "wutongpaas/filebrowser:{{ .Tag }}-amd64"
      - "wutongpaas/filebrowser:{{ .Tag }}-arm64"